# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fnLogLikNoGamma <- function(y_tkj, s_j, r_tk, mu_tj) {
    .Call('_anlpsbff_fnLogLikNoGamma', PACKAGE = 'anlpsbff', y_tkj, s_j, r_tk, mu_tj)
}

fnLogLikNoFac <- function(y_tkj, s_j, r_tk, mu_tj) {
    .Call('_anlpsbff_fnLogLikNoFac', PACKAGE = 'anlpsbff', y_tkj, s_j, r_tk, mu_tj)
}

fnOtuLogLikNoGamma <- function(s_j, r_vec, mu_j_vec, rep_K, y_j_vec) {
    .Call('_anlpsbff_fnOtuLogLikNoGamma', PACKAGE = 'anlpsbff', s_j, r_vec, mu_j_vec, rep_K, y_j_vec)
}

fnOtuLogLikNoFac <- function(s_j, r_vec, mu_j_vec, rep_K, y_j_vec) {
    .Call('_anlpsbff_fnOtuLogLikNoFac', PACKAGE = 'anlpsbff', s_j, r_vec, mu_j_vec, rep_K, y_j_vec)
}

fnTimepointLogLikNoGamma <- function(mu_t_vec, s_vec, r_tk, y_tk_vec) {
    .Call('_anlpsbff_fnTimepointLogLikNoGamma', PACKAGE = 'anlpsbff', mu_t_vec, s_vec, r_tk, y_tk_vec)
}

acceptProposal <- function(curr_log_lik, prop_log_lik, log_curr_to_prop_prob = 0, log_prop_to_curr_prob = 0) {
    .Call('_anlpsbff_acceptProposal', PACKAGE = 'anlpsbff', curr_log_lik, prop_log_lik, log_curr_to_prop_prob, log_prop_to_curr_prob)
}

fnSjTildeLogLik <- function(s_j, r_vec, mu_j_vec, rep_K, y_j_vec, h_scal, var_sig_2) {
    .Call('_anlpsbff_fnSjTildeLogLik', PACKAGE = 'anlpsbff', s_j, r_vec, mu_j_vec, rep_K, y_j_vec, h_scal, var_sig_2)
}

fnSampSVec <- function(s_vec, s_tilde_vec, r_vec, Mu_mat, rep_K, Y_mat, h_scal, var_sig_2, s_j_tilde_proposal_sd) {
    invisible(.Call('_anlpsbff_fnSampSVec', PACKAGE = 'anlpsbff', s_vec, s_tilde_vec, r_vec, Mu_mat, rep_K, Y_mat, h_scal, var_sig_2, s_j_tilde_proposal_sd))
}

fnWlLogLik <- function(ell_idx1, w_ell, param_vec, lambda_vec, c_vec, eta_vec, upsilon, a_w, b_w, u_2) {
    .Call('_anlpsbff_fnWlLogLik', PACKAGE = 'anlpsbff', ell_idx1, w_ell, param_vec, lambda_vec, c_vec, eta_vec, upsilon, a_w, b_w, u_2)
}

fnSampWVec <- function(w_vec, param_vec, lambda_vec, c_vec, eta_vec, upsilon, a_w, b_w, u_2, w_ell_proposal_sd) {
    invisible(.Call('_anlpsbff_fnSampWVec', PACKAGE = 'anlpsbff', w_vec, param_vec, lambda_vec, c_vec, eta_vec, upsilon, a_w, b_w, u_2, w_ell_proposal_sd))
}

fnSampEtaVec <- function(eta_vec, param_vec, w_vec, lambda_vec, c_vec, u_2, upsilon, b_eta_2) {
    invisible(.Call('_anlpsbff_fnSampEtaVec', PACKAGE = 'anlpsbff', eta_vec, param_vec, w_vec, lambda_vec, c_vec, u_2, upsilon, b_eta_2))
}

fnSampC <- function(param, psi_vec, w_vec, eta_vec, upsilon, u_2) {
    .Call('_anlpsbff_fnSampC', PACKAGE = 'anlpsbff', param, psi_vec, w_vec, eta_vec, upsilon, u_2)
}

fnSampCVec <- function(c_vec, d_vec, param_vec, psi_vec, w_vec, eta_vec, upsilon, u_2) {
    invisible(.Call('_anlpsbff_fnSampCVec', PACKAGE = 'anlpsbff', c_vec, d_vec, param_vec, psi_vec, w_vec, eta_vec, upsilon, u_2))
}

fnSampLambdaVec <- function(lambda_vec, param_vec, c_vec, w_vec, eta_vec, upsilon, u_2) {
    invisible(.Call('_anlpsbff_fnSampLambdaVec', PACKAGE = 'anlpsbff', lambda_vec, param_vec, c_vec, w_vec, eta_vec, upsilon, u_2))
}

fnRtkTildeLogLik <- function(r_tk, mu_t_vec, s_vec, lambda_tk, eta_ell, w_ell, upsilon_r, u_2, y_tk_vec) {
    .Call('_anlpsbff_fnRtkTildeLogLik', PACKAGE = 'anlpsbff', r_tk, mu_t_vec, s_vec, lambda_tk, eta_ell, w_ell, upsilon_r, u_2, y_tk_vec)
}

fnSampRVec <- function(r_vec, r_tilde_vec, Mu_mat, s_vec, lambda_vec, c_vec, eta_vec, w_vec, rep_K, upsilon_r, u_2, Y_mat, r_tk_tilde_proposal_sd) {
    invisible(.Call('_anlpsbff_fnSampRVec', PACKAGE = 'anlpsbff', r_vec, r_tilde_vec, Mu_mat, s_vec, lambda_vec, c_vec, eta_vec, w_vec, rep_K, upsilon_r, u_2, Y_mat, r_tk_tilde_proposal_sd))
}

fnSampRVecJoint <- function(r_vec, r_tilde_vec, Mu_mat, s_vec, lambda_vec, c_vec, eta_vec, w_vec, rep_K, upsilon_r, u_2, Y_mat, r_tk_tilde_proposal_sd) {
    invisible(.Call('_anlpsbff_fnSampRVecJoint', PACKAGE = 'anlpsbff', r_vec, r_tilde_vec, Mu_mat, s_vec, lambda_vec, c_vec, eta_vec, w_vec, rep_K, upsilon_r, u_2, Y_mat, r_tk_tilde_proposal_sd))
}

fnSampRVecJointVertical <- function(r_vec, r_tilde_vec, Mu_mat, s_vec, lambda_vec, c_vec, eta_vec, w_vec, rep_K, upsilon_r, u_2, Y_mat, r_tk_tilde_proposal_sd) {
    invisible(.Call('_anlpsbff_fnSampRVecJointVertical', PACKAGE = 'anlpsbff', r_vec, r_tilde_vec, Mu_mat, s_vec, lambda_vec, c_vec, eta_vec, w_vec, rep_K, upsilon_r, u_2, Y_mat, r_tk_tilde_proposal_sd))
}

fnAlpha0jLogLik <- function(alpha0_j, r_vec, mu_j_vec, s_j, lambda_j, eta_ell, w_ell, upsilon_r, u_2, rep_K, y_j_vec) {
    .Call('_anlpsbff_fnAlpha0jLogLik', PACKAGE = 'anlpsbff', alpha0_j, r_vec, mu_j_vec, s_j, lambda_j, eta_ell, w_ell, upsilon_r, u_2, rep_K, y_j_vec)
}

fnSampAlpha0Vec <- function(alpha0_vec, r_vec, Mu_mat, s_vec, lambda_vec, c_vec, eta_vec, w_vec, upsilon_r, u_2, rep_K, Y_mat, alpha0_j_proposal_sd) {
    invisible(.Call('_anlpsbff_fnSampAlpha0Vec', PACKAGE = 'anlpsbff', alpha0_vec, r_vec, Mu_mat, s_vec, lambda_vec, c_vec, eta_vec, w_vec, upsilon_r, u_2, rep_K, Y_mat, alpha0_j_proposal_sd))
}

fnSampAlpha0VecJoint <- function(alpha0_vec, r_vec, Mu_mat, s_vec, lambda_vec, c_vec, eta_vec, w_vec, upsilon_r, u_2, rep_K, Y_mat, alpha0_j_proposal_sd) {
    invisible(.Call('_anlpsbff_fnSampAlpha0VecJoint', PACKAGE = 'anlpsbff', alpha0_vec, r_vec, Mu_mat, s_vec, lambda_vec, c_vec, eta_vec, w_vec, upsilon_r, u_2, rep_K, Y_mat, alpha0_j_proposal_sd))
}

fnSampAlpha0VecJointVertical <- function(alpha0_vec, r_vec, Mu_mat, s_vec, lambda_vec, c_vec, eta_vec, w_vec, upsilon_r, u_2, rep_K, Y_mat, alpha0_j_proposal_sd) {
    invisible(.Call('_anlpsbff_fnSampAlpha0VecJointVertical', PACKAGE = 'anlpsbff', alpha0_vec, r_vec, Mu_mat, s_vec, lambda_vec, c_vec, eta_vec, w_vec, upsilon_r, u_2, rep_K, Y_mat, alpha0_j_proposal_sd))
}

fnThetamjLogLik <- function(theta_mj, tau_j_2, s_j, r_vec, mu_j_vec, rep_K, y_j_vec) {
    .Call('_anlpsbff_fnThetamjLogLik', PACKAGE = 'anlpsbff', theta_mj, tau_j_2, s_j, r_vec, mu_j_vec, rep_K, y_j_vec)
}

fnSampThetaMat <- function(Theta_mat, tau_2_vec, s_vec, r_vec, Mu_mat, rep_K, K_mat, Y_mat, theta_mj_proposal_sd) {
    invisible(.Call('_anlpsbff_fnSampThetaMat', PACKAGE = 'anlpsbff', Theta_mat, tau_2_vec, s_vec, r_vec, Mu_mat, rep_K, K_mat, Y_mat, theta_mj_proposal_sd))
}

fnSampSigma2Vec <- function(sigma_2_vec, Beta_mat, Gamma_mat, iota_vec, rtigamma, a_sigma, b_sigma) {
    invisible(.Call('_anlpsbff_fnSampSigma2Vec', PACKAGE = 'anlpsbff', sigma_2_vec, Beta_mat, Gamma_mat, iota_vec, rtigamma, a_sigma, b_sigma))
}

fnMujVecFromBetajp <- function(beta_jp, beta_jp_curr, mu_j_vec_curr, z_p_vec) {
    .Call('_anlpsbff_fnMujVecFromBetajp', PACKAGE = 'anlpsbff', beta_jp, beta_jp_curr, mu_j_vec_curr, z_p_vec)
}

fnBetajpPriorLik <- function(beta_jp, sigma_p_2, iota_p) {
    .Call('_anlpsbff_fnBetajpPriorLik', PACKAGE = 'anlpsbff', beta_jp, sigma_p_2, iota_p)
}

fnBetajpLogLik <- function(beta_jp, mu_j_vec, s_j, r_vec, sigma_p_2, rep_K, y_j_vec, iota_p) {
    .Call('_anlpsbff_fnBetajpLogLik', PACKAGE = 'anlpsbff', beta_jp, mu_j_vec, s_j, r_vec, sigma_p_2, rep_K, y_j_vec, iota_p)
}

fnProposeBetajp <- function(gamma_jp, sigma_p, iota_p) {
    .Call('_anlpsbff_fnProposeBetajp', PACKAGE = 'anlpsbff', gamma_jp, sigma_p, iota_p)
}

fnSampBetaMat <- function(Beta_mat, Gamma_mat, Mu_mat, s_vec, r_vec, X_mat, sigma_2_vec, rep_K, Y_mat, iota_vec, beta_jp_proposal_sd) {
    invisible(.Call('_anlpsbff_fnSampBetaMat', PACKAGE = 'anlpsbff', Beta_mat, Gamma_mat, Mu_mat, s_vec, r_vec, X_mat, sigma_2_vec, rep_K, Y_mat, iota_vec, beta_jp_proposal_sd))
}

fnProposeBetajpHat <- function(beta_jp_curr, iota_p, sigma_p_2) {
    .Call('_anlpsbff_fnProposeBetajpHat', PACKAGE = 'anlpsbff', beta_jp_curr, iota_p, sigma_p_2)
}

fnLogGammaPrior <- function(gamma_jp, pi0_p, pi1_p) {
    .Call('_anlpsbff_fnLogGammaPrior', PACKAGE = 'anlpsbff', gamma_jp, pi0_p, pi1_p)
}

fnLogBetajpTransition <- function(beta_jp_hat, gamma_jp, iota_p, sigma_p_2) {
    .Call('_anlpsbff_fnLogBetajpTransition', PACKAGE = 'anlpsbff', beta_jp_hat, gamma_jp, iota_p, sigma_p_2)
}

fnSampBetaMatGammaMatJoint <- function(Beta_mat, Gamma_mat, Mu_mat, X_mat, sigma_2_vec, iota_vec, s_vec, r_vec, rep_K, pi0_vec, pi1_vec, Y_mat, beta_jp_proposal_sd) {
    invisible(.Call('_anlpsbff_fnSampBetaMatGammaMatJoint', PACKAGE = 'anlpsbff', Beta_mat, Gamma_mat, Mu_mat, X_mat, sigma_2_vec, iota_vec, s_vec, r_vec, rep_K, pi0_vec, pi1_vec, Y_mat, beta_jp_proposal_sd))
}

fnBetaGammaAddSwpDel <- function(Beta_mat, Gamma_mat, sigma_2_vec, iota_vec, Mu_mat, X_mat, s_vec, r_vec, rep_K, pi0_vec, pi1_vec, Y_mat) {
    invisible(.Call('_anlpsbff_fnBetaGammaAddSwpDel', PACKAGE = 'anlpsbff', Beta_mat, Gamma_mat, sigma_2_vec, iota_vec, Mu_mat, X_mat, s_vec, r_vec, rep_K, pi0_vec, pi1_vec, Y_mat))
}

fnIotapLogLik <- function(iota_p, beta_p_vec, gamma_p_vec, sigma_p_2, smallest_beta, a_iota, b_iota) {
    .Call('_anlpsbff_fnIotapLogLik', PACKAGE = 'anlpsbff', iota_p, beta_p_vec, gamma_p_vec, sigma_p_2, smallest_beta, a_iota, b_iota)
}

fnSampIotaVec <- function(iota_vec, Beta_mat, Gamma_mat, sigma_2_vec, a_iota, b_iota, iota_p_proposal_sd) {
    invisible(.Call('_anlpsbff_fnSampIotaVec', PACKAGE = 'anlpsbff', iota_vec, Beta_mat, Gamma_mat, sigma_2_vec, a_iota, b_iota, iota_p_proposal_sd))
}

fnGetCurrCat <- function(categorical_vector) {
    .Call('_anlpsbff_fnGetCurrCat', PACKAGE = 'anlpsbff', categorical_vector)
}

fnImputeZ <- function(X_mat, Miss_var_ind_mat, max_miss_cat_vec, first_p_missing_idx1_vec, Mu_mat, Beta_mat, s_vec, r_vec, rep_K, rep_K_cumsum, Y_mat) {
    invisible(.Call('_anlpsbff_fnImputeZ', PACKAGE = 'anlpsbff', X_mat, Miss_var_ind_mat, max_miss_cat_vec, first_p_missing_idx1_vec, Mu_mat, Beta_mat, s_vec, r_vec, rep_K, rep_K_cumsum, Y_mat))
}

fnDLogInvGamma <- function(x, a, b) {
    .Call('_anlpsbff_fnDLogInvGamma', PACKAGE = 'anlpsbff', x, a, b)
}

fnIotapSigmapJointLogLik <- function(iota_p, sigma_p_2, beta_p_vec, gamma_p_vec, Mu_mat, s_vec, r_vec, pi0_p, pi1_p, rep_K, a_iota, b_iota, a_sigma, b_sigma, Y_mat) {
    .Call('_anlpsbff_fnIotapSigmapJointLogLik', PACKAGE = 'anlpsbff', iota_p, sigma_p_2, beta_p_vec, gamma_p_vec, Mu_mat, s_vec, r_vec, pi0_p, pi1_p, rep_K, a_iota, b_iota, a_sigma, b_sigma, Y_mat)
}

fnConvertBetaHat <- function(beta_jp_hat, iota_p, sigma_p_2) {
    .Call('_anlpsbff_fnConvertBetaHat', PACKAGE = 'anlpsbff', beta_jp_hat, iota_p, sigma_p_2)
}

fnSampIotaVecSigma2VecJoint <- function(sigma_2_vec, iota_vec, Beta_mat, Gamma_mat, Mu_mat, X_mat, s_vec, r_vec, rep_K, pi0_vec, pi1_vec, a_sigma, b_sigma, a_iota, b_iota, Y_mat, iota_p_joint_proposal_sd, sigma_p_2_joint_proposal_sd) {
    invisible(.Call('_anlpsbff_fnSampIotaVecSigma2VecJoint', PACKAGE = 'anlpsbff', sigma_2_vec, iota_vec, Beta_mat, Gamma_mat, Mu_mat, X_mat, s_vec, r_vec, rep_K, pi0_vec, pi1_vec, a_sigma, b_sigma, a_iota, b_iota, Y_mat, iota_p_joint_proposal_sd, sigma_p_2_joint_proposal_sd))
}

fnSampBetaMatGammaMatJointWholeOtu <- function(Beta_mat, Gamma_mat, Mu_mat, X_mat, sigma_2_vec, iota_vec, s_vec, r_vec, rep_K, pi0_vec, pi1_vec, Y_mat, beta_jp_joint_otu_proposal_sd) {
    invisible(.Call('_anlpsbff_fnSampBetaMatGammaMatJointWholeOtu', PACKAGE = 'anlpsbff', Beta_mat, Gamma_mat, Mu_mat, X_mat, sigma_2_vec, iota_vec, s_vec, r_vec, rep_K, pi0_vec, pi1_vec, Y_mat, beta_jp_joint_otu_proposal_sd))
}

fnSampBetaMatGammaMatJointWholeOtu2 <- function(Beta_mat, Gamma_mat, Mu_mat, X_mat, sigma_2_vec, iota_vec, s_vec, r_vec, rep_K, pi0_vec, pi1_vec, Y_mat, beta_jp_joint_otu_proposal_sd) {
    invisible(.Call('_anlpsbff_fnSampBetaMatGammaMatJointWholeOtu2', PACKAGE = 'anlpsbff', Beta_mat, Gamma_mat, Mu_mat, X_mat, sigma_2_vec, iota_vec, s_vec, r_vec, rep_K, pi0_vec, pi1_vec, Y_mat, beta_jp_joint_otu_proposal_sd))
}

fnSampBetaMatGammaMatJointWholeOtu3 <- function(Beta_mat, Gamma_mat, Mu_mat, X_mat, sigma_2_vec, iota_vec, s_vec, r_vec, rep_K, pi0_vec, pi1_vec, Y_mat, beta_jp_joint_otu_proposal_sd) {
    invisible(.Call('_anlpsbff_fnSampBetaMatGammaMatJointWholeOtu3', PACKAGE = 'anlpsbff', Beta_mat, Gamma_mat, Mu_mat, X_mat, sigma_2_vec, iota_vec, s_vec, r_vec, rep_K, pi0_vec, pi1_vec, Y_mat, beta_jp_joint_otu_proposal_sd))
}

